### ISSUE TITLE
(Feature request) AUR package

### ISSUE THREAD

**Issue by rr-** [himdel/hsetroot#1]
It would be super cool if you made a package for Arch Linux.
The one that's there uses the super outdated original code rather than this awesome fork.

**Comment by himdel** [comment]
Well, pull requests are welcome :-)

I can do a debian/ubuntu package, I could probably do a fedora package, but I have zero experience with arch, unfortunately. 

That said, I'm willing to give this a try, if you're willing to test it :-).

**Comment by rr-** [comment]
>That said, I'm willing to give this a try, if you're willing to test it :-).

Of course :+1:

**Comment by himdel** [comment]
@rr- Sorry it took so long, fortunately @boxofrox was faster... Should be resolved :)
