### ISSUE TITLE
Image manipulations don't work 

### ISSUE THREAD

**Issue by rien333** [himdel/hsetroot#10]
Great little program! My only minor annoyance is that none of the image manipulations seem to work, both in your version and in the "upstream" `hsetroot`. For example, this command does not perform any horizontal flipping (also not when appending `-write`):

```bash
hsetroot -fliph -fill test.jpg
```
I'm on arch linux, the program builds without warnings or errors and I do have imlib2 installed.

**Comment by himdel** [comment]
@rien333 That's not a bug, it's a (poorly documented) feature :).

`-fliph` and the rest work, but the arguments are positional, so, in your example, you start with a blank image, flip it, and then fill it with `test.jpg`.

```
hsetroot -fill test.jpg -fliph
```
^ works :)

**Comment by himdel** [comment]
That said, I'm not really married to that use case, maybe we *could* simplify and apply those transformations only to the final image.

I'd like to know how people use the program, for me, it's usually just `hsetroot -extend $(randomfile ~/wallpapers)`

**Comment by rien333** [comment]
I actually just started using this (hence my noobish question), so I don't really have any fancy use case just yet. I just started using this in order to switch from feh to [sxiv](https://github.com/muennich/sxiv), which meant I needed a simple wallpaper setter. Thanks for you help for explaining me how the manipulations work! They work fine indeed. 

That said, the argument parsing is a little intuitive, and I do prefer the parsing behavior of feh. An example in the documentation (maybe just in the readme?) or the removal of the positionality restriction would help. I think feh just does something like `feh arg1 arg2 im1 im2...` (where im1 goes to the first display and im2 to the second, etc. Is this possible with hsetroot?) Don't like it when programs use a single dash for long flags as well (e.g. `-cover` instead of `--cover`/`-c`), either. But yeah, neat little program overall. You can close this if you want.

**Comment by himdel** [comment]
Aah, well, welcome to the club then :)

I agree that the argument parsing is .. not up to date :), in fact it's already in my TODO list:

> rework command line option parsing, using some library (do people still use getopt_long?)

It will need some decoupling of the image manipulation code (composing multiple images, flipping, etc., not sure if we couldn't just offload that to imagemagick completely) from the code that deals with creating the final multioutput image (also so that we could allow different images per output), but should be doable.
