### ISSUE TITLE
Add zoom option

### ISSUE THREAD

**Issue by astier** [himdel/hsetroot#11]
Currently a wallpaper can only be set with the options center, tile, full and fill. Please add zoom.

**Comment by himdel** [comment]
What is "zoom"?

**Comment by himdel** [comment]
I mean, `center` just centers the image,
but `cover` scales it to the larger size,
`full` scales it to the smaller size,
`fill` stretches and
`extend` does `full` + fancy borders.

All except for center do zooming.
So, please describe in detail what is missing :)

**Comment by astier** [comment]
My version is 1.0.2 from the arch repos. I do not have the options cover and extend. With zoom I mean that if the image resolution does not fit perfectly the screen-resolution then the image is zoomed until it does fit. Like stretching but without distorting the image. Obviously some parts of the image will be then cut off. I don't want black areas but I also don't want the image to be stretched. It should be zoomed to fill the entire screen.

**Comment by himdel** [comment]
Aaah, in that case, `cover` should do exactly what you want :)

(The feature comes from the debian version of the package, https://github.com/himdel/hsetroot/commit/131ed5698172fbccbaf04147727a37fd20c768a1)

**Comment by astier** [comment]
Could you update the arch-package?

**Comment by himdel** [comment]
It is, you just have to build it from this source.

But if you mean update it in arch repos then no, I don't use arch and I don't know how that works. Feel free to do that if you know how :)

**Comment by astier** [comment]
Then could you make a new release on github? The current is 1.0.2 from 2012. As you long as don't make any new release there will be never a new release in debian (which is also 1.0.2) or arch or any other distro. Since 2012 nobody on any distro had this new features like cover. They are all waiting for a new release.

**Comment by himdel** [comment]
I don't think anybody is watching this repo in particular, so, it won't be as easy as that. 
But.. sure, why not, tagging a new release, maybe somebody will pick it up :)

**Comment by himdel** [comment]
https://github.com/himdel/hsetroot/releases/tag/1.0.3

**Comment by astier** [comment]
Thanks. Maybe #7 can also be closed.

**Comment by astier** [comment]
Cool. Now arch finally has the new version I saw just recently :)
