### ISSUE TITLE
Behaviour unexpectedly changed recently.

### ISSUE THREAD

**Issue by lwilletts** [himdel/hsetroot#18]
So, about a week ago my expected behaviour of the `hsetroot -tile` option changed on my two monitor setup, simply the best way to show you is to spot the difference between these two images:

![](https://i.imgur.com/8YaWXMe.png)
![](https://i.imgur.com/kVy55p7.png)

As you can see in the image, there is something that causes hsetroot to wrongly position the start of the image. hsetroot simply reports the following when I set an image:

```
output 0: size(2560, 1440) pos(0, 520)
output 1: size(1080, 1920) pos(2560, 0)
```

None of the other options given results in the intended behaviour of the second image. Mainly the fact that they don't draw to non screen regions and instead produce black areas where the screen's physical pixels are, and in addition -cover for example zooms out of the images whereas I would like something more akin to -center over multiple screens.

This changed happened about roughly 6 days ago as the first image was taken on the 16th and the behaviour changed on 17th when I booted up again. I don't think this is an issue is because of hsetroot recent commits (I don't believe so as I've built an older version and the same issue persists) or an upstream issue/another weird issue with my setup but was hoping someone could point me in the right direction.

**Comment by himdel** [comment]
Interesting, but I did notice a similar bug at some point - I think something is not quite right with how we position the images for multi-screen setups and gets exposed when you have different screen sizes and positions.

Theoretically, if the order the screens get detected changed, that could do it.

(I think this is a real hsetroot bug, but I don't quite yet know when it happens or how.)

You can probably verify if it's about the screen order by reversing it in hsetroot:

```diff
diff --git a/hsetroot.c b/hsetroot.c
index b3ec3c1..e21940f 100644
--- a/hsetroot.c
+++ b/hsetroot.c
@@ -160,7 +160,7 @@ load_image(ImageMode mode, const char *arg, int alpha, Imlib_Image rootimg, Xine
 
   imlib_context_set_image(rootimg);
 
-  for (int i = 0; i < noutputs; i++) {
+  for (int i = noutputs - 1; i >= 0; i--) {
     XineramaScreenInfo o = outputs[i];
     printf("output %d: size(%d, %d) pos(%d, %d)\n", i, o.width, o.height, o.x_org, o.y_org);
 
```

**Comment by MaximeWack** [comment]
Hi, I noticed a change of behavior regarding multiple screens too.

Here is my original setup:

![](https://imgur.com/PYcU3SS?raw=true)
(https://imgur.com/PYcU3SS)

It consists of two screens, and one big background image set with `hsetroot -fill bg.png`. I added dashed and stripes to visually separate the screens as `scrot` captures the whole region.

Here is the new behavior of `hsetroot -fill`:

![](https://imgur.com/ok2EDU8?raw=true)
(https://imgur.com/ok2EDU8)

I tried some of the new options (`-cover` and `-extend`) but couldn't replicate the original setup.
Is there a way to `-fill` an image spanning all screens ?

Thanks

**Comment by himdel** [comment]
Oh, cool ... @MaximeWack , @lwilletts can I ask you two for the original wallpapers please?
Or, to do the same thing you did, with a wallpaper with a grid, or something rectangular? (https://wallup.net/test-pattern-2/ would be perfect)

The thing is .. I have no idea which of those screenshots is right and which is wrong, because I don't know the image you're using, so I don't know how it's *supposed* to look :).

**Comment by himdel** [comment]
But, @MaximeWack looks like your problem may be different - since hsetroot added support for multiple screens, we've dropped the ability to just set a wallpaper that covers all the screens instead of each screen individually.

It sounds like this is something more people could find useful, so I'll try to add an option to ignore outputs and just use the whole screen.

**Comment by MaximeWack** [comment]
Here's the background image:

![](https://imgur.com/bBm0DZA.png)

**Comment by MaximeWack** [comment]
Thanks @himdel, that would be really cool!

On a side note, now that there is support for multiple screens, if there was a way to set different wallpapers per screen I could work around this. I see a `-screen` option but wasn't able to use it.

**Comment by himdel** [comment]
@MaximeWack that's planned too :)

`-screen` is useless outside multi-head setups I think,

the normal way people use multiple screens is that X treats the whole thing as one screen together - so you can't just change a wallpaper on one of them, without keeping a copy of the whole thing.

But I am planning to basically extend all those `-tile` `-cover` etc. to be able to take multiple images, 
so the idea is you would say `hsetroot -tile first.png second.png third.png` and it would go over the screens in a left-right-top-bottom order and use each image for just one screen (#12).

But for that, I need to rewrite option parsing to support that (#13).

**Comment by lwilletts** [comment]
Hi thanks for responding. Changing the above line of code  as suggested just results in hsetroot changing the root window to black. as per request, here's my original image: ![](https://images.unsplash.com/photo-1508091388232-40090efcc790?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80)

Here's your test shot using `hsetroot -tile test: ![](https://a.uguu.se/T5yjbZeqWWS6_23-08-19-17%3A03%3A54.png)

Here's my display output:  ![](https://a.uguu.se/mWeftGyBd3YS_23-08-19-17%3A13%3A21.png)

Thanks for continuing to develop hsetroot, I particularly look forward to a clean way to set multiple images to different screens.

**Comment by himdel** [comment]
> ... I particularly look forward to a clean way to set multiple images to different screens.

@lwilletts with #20, it should be possible to *set* a multi-screen image, except you would have to create that composite image elsewhere.

Still working on the second part of that, and looking into the alignment issue :).

**Comment by himdel** [comment]
> and looking into the alignment issue

Oh, found it actually.. this is specific to the `-tile` mode, when we tile the image per display, we don't stop at the display boundary, overwriting what's prepared for the surrounding displays.

(https://github.com/himdel/hsetroot/blob/master/hsetroot.c#L205-L210)

I'll figure out the right math for that in the morning :)

**Comment by lwilletts** [comment]
Back again and willing to try and help out. I want to use a composite image that I made in gimp to perfectly fit my monitors (total resolution of 3640x1920):

[https://i.imgur.com/9MGxJUV.jpg](url)

Using the latest git version of hsetroot: `hsetroot -full image.png` gives the following correct per monitor  result:

[https://i.imgur.com/M8W2z4z.jpg](url)

But using: `hsetroot -root -full image.png` gives me a black screen:

[https://i.imgur.com/95rGAjq.png](url)

It reports an absolutely baffling pos too: 

```
output 0: size(3640, 1920) pos(-27896, -32645)
```

Now the only thing I can think that I am doing differently is that my primary monitor is not set at 0,0 but even setting it back to 0,0 I still get a weird result:

output 0: size(3640, 1920) pos(8968, 16577)

**Comment by himdel** [comment]
(Sorry for not reacting, things are a bit busy now, I hope to get back to hsetroot the next weekend.)

**Comment by tarcisioe** [comment]
@himdel @lwilletts I believe #26 fixes the position issue.

**Comment by lwilletts** [comment]
Thanks for the fix, working as expected now.

**Comment by lwilletts** [comment]
Would it also be possible to get a new release seeing as this fixes a pretty major bug introduced from the last release.

**Comment by himdel** [comment]
Sure, sorry, I was hoping the fix the overlap issue as well, but maybe it's better to just do a release now :). Tagging..
