### ISSUE TITLE
Makefile no hard destdir

### ISSUE THREAD

**Issue by biopsin** [himdel/hsetroot#22]
Hey, thanks for keeping this application going!
Mind not hardcode install destination, not all distro allow it
and let pkg templates override it if required.

```
PREFIX?=/usr/local

install: hsetroot hsr-outputs
    install -Dm755 hsetroot $(DESTDIR)$(PREFIX)/bin/hsetroot
    install -Dm755 hsr-outputs $(DESTDIR)$(PREFIX)/bin/hsr-outputs
```

**Comment by himdel** [comment]
Thanks @biopsin , should be fixed now :)
