### ISSUE TITLE
Wrong version in README

### ISSUE THREAD

**Issue by astier** [himdel/hsetroot#23]
Hi there. Your readme says

> This repo contains hsetroot 1.0.2 with the following changes: ...

However, its already 1.0.4 if I got it right. Not a big deal. Just wanted to make u aware of it :)

**Comment by himdel** [comment]
Hey, you're right, thanks :)

Originally, this was meant to mean "this is upstream hsetroot 1.0.2 + patches",
but since the original author is not working on hsetroot, and this has become the de facto upstream, maybe it is time to update that.

Will do :)

**Comment by astier** [comment]
Any progress?
