### ISSUE TITLE
Possible memory leak inherited from bsetroot

### ISSUE THREAD

**Issue by BS-Labs** [himdel/hsetroot#35]
Someone who understands this a little better should probably double check, but it appears a typo in hsetroot (in "setRootAtoms()"  - line 76 of current HEAD) may be preventing XKillClient from being called - which as I understand it may prevent the X server from freeing the resource. As far as I can determine the correct root window property name is "_XROOTPMAP_ID", but the requested property name is "_XROOTMAP_ID". Further down in the code, where the property atom is guaranteed, the correct name is used. If this is an error, it appears to be inherited from fluxbox, where it's been hanging around since at least 2005. Probably not super important, but it's been bugging me.

**Comment by vincentbernat** [comment]
I was looking at the same piece of code today and I have the same conclusion. Looking at the [usage](https://codesearch.debian.net/search?q=_XROOTMAP_ID) of `_XROOTMAP_ID`, if we remove comments, only hsetroot, bsetroot, pcmanfm and spacefm are using it. While the [usage](https://codesearch.debian.net/search?q=_XROOTPMAP_ID) of `_XROOTPMAP_ID` is far more widespread, including xscreensaver whose author likely knows what he is doing.

**Comment by himdel** [comment]
Hm, thanks for reporting! This may actually be the reason `xwd` fails to screenshot sometimes, will take a look :)

**Comment by vincentbernat** [comment]
For information, I have taken over the Debian package and updated it to 1.0.5 (+ this patch). Ping me if you have any Debian-related problem with hsetroot.

**Comment by himdel** [comment]
@vincentbernat ++, that's good news :) I can confirm the sid version of hsetroot works for me :)
