### ISSUE TITLE
set wallpaper only on specific wallpaper?

### ISSUE THREAD

**Issue by wael444** [himdel/hsetroot#40]
`-screens` doesnt seem to work.

also there is no man page.

**Comment by himdel** [comment]
`-screens` is for Xinerama screens, it's probably not the one you want.

In modern X, all the displays are really part of one screen .. and we're always painting the whole screen.
So .. it's not possible to change a wallpaper on just one screen without repainting the other screens, which means you'd need to provide all the images again.

(I still want to implement that at some point, but that's https://github.com/himdel/hsetroot/issues/14)

**Comment by wael444** [comment]
since #40 is a duplicate, i will close this.
